### PR TITLE
move and update linux-hardened patch

### PR DESCRIPTION
**Pull request by andrewfader**
This wasn't working for me today. I think it's because `linux-hardened.patch` was in the wrong location. But I ended up creating the patch using vim per the instructions and building the whole thing. Then to open this PR I moved `linux-hardened-5.18.11-hardened1.patch` into the directory. I'm not sure if I did it right because the diff seems too large.

### CODE REVIEW

**Comment by andrewfader** [comment]
Also @itoffshore it doesn't seem to prevent the build from working but I see a couple of errors
```abk -u linux-hardened
/usr/bin/abk: line 119: [: : integer expression expected
```
I also get a permission issue when running the genkeys.py if I use `abk -b` but I can go to the build dir and run `makepkg`.

**Comment by itoffshore** [comment]
I updated `arch-sign-modules` to `0.4.2` last night with the [new `linux-hardened` patch](https://github.com/itoffshore/Arch-SKM/pull/48) - I get `urlwatch` updates on telegram for the main Arch kernels `abk` supports & test the patches usually straight away.

- What does `echo $XDG_VTNR` show in your shell ? (perhaps you are [not using systemd](https://unix.stackexchange.com/questions/521037/what-is-the-environment-variable-xdg-vtnr) ?)
- Also what does `ls -l /bin/sh` point to on your system ? (mine points to `/bin/bash`) 

---

I built `linux-hardened` before I made the PR - perhaps try `abk` version `0.4.2`
```
[stuart@endeavour ~/devops/distrobuilder/scripts/menu]$ abk -i linux-hardened

    1) : linux-hardened-5.17.5.hardened1-2-x86_64.pkg.tar.zst
    2) : linux-hardened-5.17.6.hardened1-2-x86_64.pkg.tar.zst
    3) : linux-hardened-5.17.7.hardened1-1-x86_64.pkg.tar.zst
    4) : linux-hardened-5.17.11.hardened2-1-x86_64.pkg.tar.zst
    5) : linux-hardened-5.18.6.hardened1-1-x86_64.pkg.tar.zst
    6) : linux-hardened-5.18.11.hardened1-1-x86_64.pkg.tar.zst

:: Choose kernel to install [1 - 6] : 
```
---

Yes your `diff` is a bit large you have managed to include some kernel sources.

For the future you would only need to:
```
git clone git@github.com:itoffshore/Arch-SKM.git
cd Arch-SKM
git checkout my-branch
cp /path/to/linux-hardened.patch ./patches
git diff # check the changes
git commit
git push -u origin my-branch
```
& make a PR ;o)

---

For the error you see - probably your shell doesn't like the braces - you could debug it by playing around with the following:
```
#!/bin/sh

check_session() {
        # https://wiki.archlinux.org/title/Xinit#Autostart_X_at_login
        if [ -n "${DISPLAY}" ] && [ "${XDG_VTNR}" -eq 1 ]; then
                echo "graphical"
        else
                echo "terminal"
        fi
}

check_session
```

On my desktop system it echos `graphical`

**Comment by itoffshore** [comment]
For the permissions issue I would check:
```
[stuart@endeavour ~/devops/distrobuilder/scripts/menu]$ ls -l /usr/src/certs-local/genkeys.py 
-rwxr-xr-x 1 root root 13459 Jun 27 19:12 /usr/src/certs-local/genkeys.py
```
you can fix it with:

`sudo chmod 755 /usr/src/certs-local/genkeys.py`

**Comment by andrewfader** [comment]
Take a look at the present state of the repo - isn't linux-hardened patch in the root instead of in patches?

```
> ls -l /usr/src/certs-local/genkeys.py
-rwxr-xr-x 1 root root 13459 Jul 13 12:43 /usr/src/certs-local/genkeys.py
❯ uname -a
Linux obsidian 5.18.11-hardened1-1-hardened #1 SMP PREEMPT_DYNAMIC Wed, 13 Jul 2022 17:28:34 +0000 x86_64 GNU/Linux
❯ echo $XDG_VTNR

❯ echo $DISPLAY
:0
❯ ls -l /bin/sh
lrwxrwxrwx 1 root root 4 Jan  8  2022 /bin/sh -> bash
❯ pacman -Q | grep systemd
lib32-systemd 251.3-1
python-systemd 234-11
systemd 251.3-1
systemd-libs 251.3-1
systemd-swap 4.4.0-2
systemd-sysvcompat 251.3-1
❯ pacman -Q | grep arch-sign
arch-sign-modules 0.4.2-0

```

**Comment by andrewfader** [comment]
Here, this commit moves the patch from the root into the dir

**Comment by itoffshore** [comment]
yes well spotted thank you - it was 1am when I made the PR yesterday ;o)

better [luck with today's](https://github.com/itoffshore/Arch-SKM/pull/50)

I'll update AUR to `0.4.3`

**Comment by andrewfader** [comment]
Thanks I'll try it @itoffshore, maybe you should make some kind of github action ci build to run and make sure it's buildable?
Also I am trying to figure out why I seem not to have no $XDG_VTNR although I do use systemd-logind, gdm, is it possible my system isn't using pam_systemd?

**Comment by andrewfader** [comment]
Nevermind that because I do have
```
echo $XDG_RUNTIME_DIR
/run/user/1000
```
I use Wayland, maybe that's why?

**Comment by itoffshore** [comment]
`0.4.3` on AUR now

I did look at some CI to build a kernel with Github Actions but they [only have Ubuntu runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners). Perhaps it's possible via CircleCI on Github. It would have picked up this issue quicker.

On my system I have `pam` & `pambase` installed (they are both `core` packages so should be installed by default):

`/usr/lib/security/pam_systemd.so` (part of `systemd` package)

I use `systemd-logind` too but run [rootless xorg](https://wiki.archlinux.org/title/Xorg#Rootless_Xorg) with no display manager - if you use GDM it does this for you.

Maybe you have some `*.pacnew` files in `/etc/gdm` or `/etc/pam.d` that need merging / replacing current configuration ?

**Comment by itoffshore** [comment]
yes probably due to Wayland

**Comment by itoffshore** [comment]
`export XDG_VTNR=1` in your `~/.bashrc` or `~/.bash_profile` as a quick fix (assuming you never build from the console / headless)

**Comment by andrewfader** [comment]
OK thanks. 0.4.3 building fine

**Comment by itoffshore** [comment]
Many thanks for testing & finding this bug.

I'll have a look at using the Gitlab Ubuntu runner - if it has LXD in it I could pull an Arch image & build a kernel.

**Pull request closed without merging**
