### PR TITLE
add patch support for linux-hardened-git

### LINKED ISSUE #5: linux-hardened-git patch
```
❯ cat /usr/share/arch-sign-modules/patches/linux-hardened-git.patch
--- PKGBUILD.orig	2022-08-01 02:44:32.591942497 -0400
+++ PKGBUILD	2022-08-01 02:47:30.136018858 -0400
@@ -46,7 +46,34 @@ pkgver() {
 }
 
 prepare() {
-  cd $_srcname
+  # Out-of-tree module signing
+  #
+  ######################################################
+  # this is added at the start of prepare() & replaces #
+  # 'cd $_srcname'                                     #
+  ######################################################
+  # uncomment for linux-xanmod-cacule & some other AUR kernels
+  # to match the Package Maintainer's variable for the kernel
+  # sources directory.
+  #
+  # local _srcname=linux-${_major}
+
+  msg2 "Rebuilding local signing key..."
+
+  cp -rf /usr/src/certs-local ./
+  cd certs-local
+
+  msg2 "Updating kernel config with new key..."
+
+  # NB: config path must be quoted for file globbing to work
+  # some kernels have multiple config files (e.g linux-libre)
+  # to see configurable options run:
+  # /usr/src/certs-local/genkeys.py -h
+  ./genkeys.py -v --config '../config*'
+
+  cd ../$_srcname
+
+# cd $_srcname
 
   echo "Setting version..."
   rm -f localversion* include/config/kernel.release
@@ -76,7 +103,7 @@ prepare() {
 build() {
   cd $_srcname
   make all
-  make htmldocs
+  #ke htmldocs
 }
 
 _package() {
@@ -187,6 +214,33 @@ _package-headers() {
   echo "Adding symlink..."
   mkdir -p "$pkgdir/usr/src"
   ln -sr "$builddir" "$pkgdir/usr/src/$pkgbase"
+
+  # Out-of-tree module signing
+  ##################################################
+  # this is added at the end of _package-headers() #
+  ##################################################
+  # This is run in the kernel source / build directory
+  #
+  # some AUR kernels may also need to set $builddir to match
+  # the Package Maintainer's variable for the build dir
+  # inside the package:
+  #
+  # local builddir="$pkgdir/usr/lib/modules/${_kernver}/build"
+
+  msg2 "Local Signing certs for out-of-tree modules..."
+
+  certs_local_src="../certs-local"
+  certs_local_dst="${builddir}/certs-local"
+
+  # install certificates
+  ${certs_local_src}/install-certs.py $certs_local_dst
+
+  # install dkms tools
+  dkms_src="$certs_local_src/dkms"
+  dkms_dst="${pkgdir}/etc/dkms"
+  mkdir -p $dkms_dst
+
+  rsync -a $dkms_src/{kernel-sign.conf,kernel-sign.sh} $dkms_dst/
 }
 
 _package-docs() {
@@ -208,7 +262,7 @@ _package-docs() {
   ln -sr "$builddir/Documentation" "$pkgdir/usr/share/doc/$pkgbase"
 }
 
-pkgname=(linux-hardened-git linux-hardened-headers-git linux-hardened-docs-git)
+pkgname=(linux-hardened-git linux-hardened-headers-git)
 for _p in "${pkgname[@]}"; do
   _p=${_p/-git/}
   eval "package_$_p-git() {
```

### PR DESCRIPTION
**Pull request by itoffshore**
* fixes https://github.com/gene-git/Arch-SKM/issues/5

### CODE REVIEW

**Comment by andrewfader** [comment]
Thank you!

**Comment by itoffshore** [comment]
@andrewfader - `0.4.4` with the new patch is [on AUR](https://aur.archlinux.org/packages/arch-sign-modules). 

If you have a patch already in `/usr/share/arch-sign-modules/patches/linux-hardened-git.patch` it will need to be moved or deleted before installing `0.4.4`.

**Comment by itoffshore** [comment]
@andrewfader - I just added a `-r` option to rebuild a previously archived kernel `PKGBUILD` in [version `0.5.0`](https://github.com/itoffshore/Arch-SKM/releases/tag/0.5.0) (for cases where `gcc` has changed & you want to revert to a previous kernel which needs to be rebuilt)

**Comment by andrewfader** [comment]
Cool thanks!

**Comment by andrewfader** [comment]
Looks like this will need updates for v6.0 @itoffshore, I tried building the patch but didn't work. Thanks for your help!

**Comment by itoffshore** [comment]
@andrewfader - the non git version builds without alteration:

---
Screenshot_2022-11-04_22-47-10

I created a `linux-hardened-git.patch` with the automatic builtin functionality in `abk`:

---
Screenshot_2022-11-04_23-34-39

& will merge it shortly.

**Comment by itoffshore** [comment]
@andrewfader - [AUR updated to `0.5.3`](https://aur.archlinux.org/packages/arch-sign-modules)

**Comment by andrewfader** [comment]
Thank you!

**Pull request merged**
